[package]
name = "ergo-merkle-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.9"
base16 = "0.2.1"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_repr = { version = "0.1.7", optional = true }
serde_json = { version = "1.0", optional = true }

[features]
default = ["json"]
json = ["serde", "serde_json", "serde_repr"]
