[package]
name = "ergotree-interpreter"
version = "0.13.3"
license = "CC0-1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>"]
edition = "2018"
description = "ErgoTree interpreter"
repository = "https://github.com/ergoplatform/sigma-rust"
exclude = [
    "proptest-regressions/*"
]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sigma-util = { version = "^0.2.0", path = "../sigma-util" }
ergotree-ir = { version = "^0.13.0", path = "../ergotree-ir" }
indexmap = "1.3.2"
k256 = { version = "0.7.2", features = ["zeroize", "arithmetic", "ecdsa"] }
elliptic-curve = {version = "0.9.6", features = [ "zeroize"]}
blake2 = "0.9"
rand = "0.7"
lazy_static = "1.4"
thiserror = "1"
derive_more = "0.99"
num-traits = "0.2.14"
proptest = {version = "1.0.0", optional = true }
proptest-derive = {version = "0.3.0", optional = true }
base16 = "0.2.1"
num-bigint = "0.4.0"
bounded-vec = { version = "^0.4.0" } 

[features]
default = []
arbitrary = ["proptest", "proptest-derive"]

[dev-dependencies]
ergotree-ir = { version = "^0.13.0", path = "../ergotree-ir", features = ["arbitrary"] }
ergoscript-compiler = { version = "^0.9.0", path = "../ergoscript-compiler" }
proptest = "1.0.0"
sigma-test-util = { version = "0.2.0", path = "../sigma-test-util" }

